#!/bin/bash

#clear screen
clear

#goto home dir and make repository dir
cd ~
mkdir isoRepo
cd isoRepo

#Ask if they want large (l) or small (s) repo of ISOs
read -p "please enter if you want large (l), or small repository of ISOs. Large takes more space, but has more ISOs. (l/s)" repoAmount
if [[ $repoAmount == l ]]; then
  echo "Large Repo Downloading"
  #Download the ISOs
  #Kali
  curl -L -o -c $isoRepo "https://cdimage.kali.org/kali-2025.2/kali-linux-2025.2-installer-amd64.iso"
  #Linux Mint Cinnamon
  curl -L -o -c $isoRepo "https://mirrors.seas.harvard.edu/linuxmint/stable/22.2/linuxmint-22.2-cinnamon-64bit.iso"
  #Linux Mint XFCE
  curl -L -o -c $isoRepo "https://mirrors.seas.harvard.edu/linuxmint/stable/22.2/linuxmint-22.2-xfce-64bit.iso"
  #Debian KDE
  curl -L -o -c $isoRepo "https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/debian-live-13.0.0-amd64-kde.iso"
  #Debian Gnome
  curl -L -o -c $isoRepo "https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/debian-live-13.0.0-amd64-gnome.iso"
  #Arch
  curl -L -o -c $isoRepo "https://mirror.clarkson.edu/archlinux/iso/2025.09.01/archlinux-2025.09.01-x86_64.iso"
  #Puppy
  curl -L -o -c $isoRepo "https://distro.ibiblio.org/puppylinux/puppy-bookwormpup/BookwormPup64/10.0.10/BookwormPup64_10.0.10.iso"
  #Fedora Gnome
  curl -L -o -c $isoRepo "https://download.fedoraproject.org/pub/fedora/linux/releases/42/Workstation/x86_64/iso/Fedora-Workstation-Live-42-1.1.x86_64.iso"
  #Fedora KDE Plasma
  curl -L -o -c $isoRepo "https://download.fedoraproject.org/pub/fedora/linux/releases/42/KDE/x86_64/iso/Fedora-KDE-Desktop-Live-42-1.1.x86_64.iso"
  #Slackware
  curl -L -o -c $isoRepo "https://mirrors.slackware.com/slackware/slackware-iso/slackware64-15.0-iso/slackware64-15.0-install-dvd.iso"
elif [[ $repoAmount == s ]]; then
  echo "Small Repo Downloading
  #Download the ISOs
  #Kali
  curl -L -o -c $isoRepo "https://cdimage.kali.org/kali-2025.2/kali-linux-2025.2-installer-amd64.iso"
  #Linux Mint
  curl -L -o -c $isoRepo "https://mirrors.seas.harvard.edu/linuxmint/stable/22.2/linuxmint-22.2-cinnamon-64bit.iso"
  #Debian
  curl -L -o -c $isoRepo "https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/debian-live-13.0.0-amd64-kde.iso"
  #Arch
  curl -L -o -c $isoRepo "https://mirror.clarkson.edu/archlinux/iso/2025.09.01/archlinux-2025.09.01-x86_64.iso"
  #Puppy
  curl -L -o -c $isoRepo "https://distro.ibiblio.org/puppylinux/puppy-bookwormpup/BookwormPup64/10.0.10/BookwormPup64_10.0.10.iso"
else;
  echo "error, you can only enter l or s. Script killed
  exit
fi
